### ISSUE TITLE
Step 2 - throw different error if signing server can not be contacted

### ISSUE THREAD

**Issue by stylesuxx** [fpv-wtf/wtfos-configurator#130]
There is at least one case where step 2 fails because the signing server can not be contacted via CORS proxy.
We should throw a different error in this case and probably only enable the CORS proxy for the signing server in dev since the PROD IP should be white-listed anyway.

**Comment by j005u** [comment]
It's not related to IPs, but rather the request Origin.

Don't we have to also move testing to e.g. fpv.wtf/testing/ because of GH pages specifics? So not sure if there's much point in writing an exception for dev.

**Comment by stylesuxx** [comment]
Yeah right  was a bit of a brain fart... Maybe we could ask for the whole domain, including subs to be white-listed?

Then I would only need a flag for local dev.

**Comment by j005u** [comment]
We could ask the whole domain to be white listed yes, but my point was don't we have to move testing to fpv.wtf/testing/ as a path/deployment folder, because we can't easily host two different subdomains from the same GH repo Pages?

So the question becomes moot if we're moving the main site to fpv.wtf?

**Comment by stylesuxx** [comment]
Oh yeah - you are right.
