### ISSUE TITLE
OSD freezing

### ISSUE THREAD

**Issue by klavifon** [fpv-wtf/wtfos-configurator#272]
Hello,

I have an issue where OSD freezes when video signal becomes weak. Sometimes the OSD comes back (by that I mean it starts updating its values) and sometimes it just stays frozen. I have to disarm and unplug the quad and then it comes back. I don't know the exact number of mbps but it happens when video link is pretty weak. I'm kind of desperate because I really need an OSD elements on my long range quad and I very much rely on elements like home arrow and distance from home etc...
What could be the problem? 
Thanks,
Ales

**Comment by stylesuxx** [comment]
Yes, this might happen. AFAIK this also depends on the FC firmware you are using. BF sends continuous updated, and inav AFAIK only sends incremental updates. I would ask you to post your issue in the [msp-osd repo](https://github.com/fpv-wtf/msp-osd) since this is not really an issue with the configurator.

**Comment by klavifon** [comment]
Thanks for the info. I already opened an issue on msp-osd repo. Hope to find any solutions.
