### ISSUE TITLE
V2 goggles with 01.03.00.00 showing but downgraded via butter won't root

### ISSUE THREAD

**Issue by kc5cw** [fpv-wtf/wtfos-configurator#274]
Try to root my v2 goggles that came with 01.03.  I downgrade with butter and it looks like it is successful.  After butter it asks for language selection in goggles.
I connect to wtf and try to root:
show com4 connected.  I select and click connect.
v1.0.1 - Trace ID: 047729f9-81eb-49f7-b985-0490335a7987
If I let it sit for a while it shows more attempts but all of them result in this:
00:03 Attempting Step 1...

00:46 Failed after 10 retries.

**Comment by Sillybeast170** [comment]
Make sure you are in DJI FPV mode on the goggles. This happened to me earlier and the problem was that I was on the regular DJI mode. Change this in the settings in the goggles.

**Comment by kc5cw** [comment]
I should have mentioned. It doesn’t have that option at the bottom of the menu even after the butter downgrade

**Comment by Sillybeast170** [comment]
What options do you see in settings?

**Comment by kc5cw** [comment]
Bottom one is reset all

I tried to bind to my caddix vista but the goggles just beep forever even when I put the vista in bind mode (red light). 

I found this https://forum.dji.com/forum.php?mod=viewthread&tid=239884&mobile=2

Which references binding to a FPV drone.

**Comment by Sillybeast170** [comment]
Don’t you also have to downgrade and root ur caddx as well? I’m thinking this could be why you’re having binding issues? Since you downgraded ur goggles. Worst case, you can atleast connect to dji assistant 2 fpv version and update back to 1.03 and then should be able to bind again.

**Comment by kc5cw** [comment]
I'm in dji mode. I'm not sure what the order of operations should be. 
I'll try activating my goggles which will require an upgrade of some kind I believe. Then see if I can bind. Then downgrade with butter. 
Sound like a good plan?

**Comment by Sillybeast170** [comment]
Sounds good. If your goggles are still on the downgrade version, you will get a pop up when connecting ur goggles to dji assistant 2 fpv edition that states something along the lines of “your version does not match or incompatible…” and should give you an update button. Go ahead and do that and it should put you back on ur original firmware. Then, try binding again. If it works, set ur goggles on the dji FPV mode (which you should already be on since that’s what you usually use to connect to ur caddx vista) and then downgrade and retry root. If you have binding issues after doing all of this successfully, it might be because there is a step for downgrading/rooting ur caddx vista as well but don’t quote me on that. Joshua bardwell on YouTube has a good vid on this stuff.

**Comment by stylesuxx** [comment]
You need to be in DYI mode...

**Comment by Sillybeast170** [comment]
Ah shit. No wonder this guys confused. I’ve been saying it wrong this whole time.

**Comment by Sillybeast170** [comment]
We’re you able to update using dji assistant 2 fpv edition??

**Comment by kc5cw** [comment]
So I tried butter multiple times and that didn't work but I was able to use the DJI assistant to reload and then downgrade firmware, and now I am able to convert it into the FPV mode. Thanks everybody.
