### ISSUE TITLE
no compatible devices found

### ISSUE THREAD

**Issue by joeoekfpokfkwf** [fpv-wtf/wtfos-configurator#284]

**Comment by stylesuxx** [comment]
Pleas provide more context and information. Which OS, which browser, which device, what are you trying to do?

**Comment by Mr-Squid-FPV** [comment]
im also having the same problem, after rolling back my goggle firmware via butter. i then went on to move to the next stage of installing the root for full betaflight osd,  on the webpage ( https://fpv.wtf the option for connecting the goggle or air units via usb displays ( no compatible devices found ) i then went on to process of elimination and went through aroud 12 type C information cables. 2 laptops and one desk top the status still remains ( no compatible devices found)  if there is somewhere i can send a video of whats happening i will gladly walk through it with someone and maybe they can throw some light on the situation.
many thanks 
Squid

**Comment by stylesuxx** [comment]
Did you root it first? https://fpv.wtf/root

**Comment by Mr-Squid-FPV** [comment]
Hi buddy,
so this is the steps i took following JB's VIDEO ( https://youtu.be/63Smmc0bNcg )
i then went on to the step of rooting them once the firmware had rolled back.
with the wtfos page open i then connected the goggles to the computer and pressed the connect button but as described above it said no compatible devices found, i pressumed this was due to my cable so i tried multiple cables and still nothing then another 2 computers and still nothing i also went on to try a different browser but unfortunatily still the same outcome

**Comment by stylesuxx** [comment]
Did you try to connect on the root page? Because the device will not be found on the home page if not rooted yet.

**Comment by jstoeffler** [comment]
Hi,

I had the same problem and I finally managed to fix it, here's how: https://github.com/fpv-wtf/wtfos-configurator/issues/189#issuecomment-1438978328

**Comment by stylesuxx** [comment]
@joeoekfpokfkwf any more updates on this, otherwise I will close this issue.
