### ISSUE TITLE
Root from Browser

### ISSUE THREAD

**Issue by stylesuxx** [fpv-wtf/wtfos-configurator#4]
* [x] Test Googles V2
* [x] Test on Vista
* [x] Test on OG Air-Unit
* [ ] Test Goggles V1

Todo:
* [x] Step 4 - Success! Rebooting... check multiple times
* [ ] Use ping commands before invoking actual command
* [x] Test timeout between device coming online and invoking the actual command

**Comment by j005u** [comment]
The dronehacks API endpoint is now CORS enabled for fpv.wtf and a simple local proxy can be used for development cases.

We need to decide if/who will attempt to either port the existing exploit code to use WebSerial or if we should do it from scratch.

**Comment by j005u** [comment]
Rooting could be an automatic first step in the wtfos install workflow.

I realize this would require some modification of the global state handling. But if you can pair to a DJI device with WebUSB (vendor id 0x2ca3, product id 0x1f for all devices), but it doesn't have the adb interface on it, that means we need to install wtfos, starting by rooting.

**Comment by stylesuxx** [comment]
Yes, this is something I had planned. I just wanted to get everything working separately before putting it all together.

**Comment by stylesuxx** [comment]
@j005u could you please give the rooting functionality a spin on the Goggle V1? I have now consistent results with Goggles V2 in DIY mode and the Caddx Vista.

In the coming days I will try rooting a "fresh" Vista. But from what I understand, uninstalling WTFOS and locking the device is basically the same thing as trying with a "fresh" Vista, no?

**Comment by j005u** [comment]
Success on Goggles V1 now.

A couple of notes:
- For some reason I get "Step 4 - Success! Rebooting..." 3 times in a row.
- The reason the device "goes away and comes back" is that during bootup various scripts can change the usb gadget modes several times
- It might be beneficial to add a small delay between detecting the device and attempting any steps after a reboot, checking that the device is still present after the delay
- Also, based on yesterdays logs, I think you might be sending some messages in some cases before the service on the other end is up and listening. I think each service should have a ping cmd that can be used to probe for the service being up before executing. I think cmdset 0 cmdid 1 for each service should be usable for these purposes?

The usb interfaces/services coming and going in an unreliable fashion is the reason I stuck with hardcoded delays in margerine. None of the above is a critical issue by any means, just adding some comments in case you ever want to make the process cleaner. But I'm happy with it either way.

I'm sure you'll come across this in integration, but I'll make a quick note of it here: immediately after rooting, when I navigate to the wtfos page (or other adb reliant pages), they are completely blank. A refresh fixes this.

For going back to stock:
I made wtfos-system uninstall persist the adb unlock and since it's targeting a different file than margerine used to, running margerine.js lock won't "relock" properly anymore.

You can use this to disable the remaing adb enables on *150:
```
sed -i '/#wtfos/,/#\/wtfos/d' /system/bin/${WTFOS_TARGET_SCRIPT}
restorecon /system/bin/${WTFOS_TARGET_SCRIPT}
```
where WTFOS_TARGET_SCRIPT is either start_dji_system.sh or prestart_dji_system.sh on *150 and gl170 respectively.

It's worth noting that this doesn't actually fully undo the "root", because the permanent secure_debug 1 flag is never removed (it's a bad idea for several reasons to allow that to be reset to 0). On gl170 you just loose the selinux unlock. On *150 you loose adb access however. This effectively makes the initial OTA one time secure debug action a NOP since the device is already permanently secure_debug 1. The latter matters a little bit on gl170, because it makes it harder to test for situation that causes you to require to run the root multiple times and reboot - since secure_debug=1 it's impossible to repro the e0 situation on Goggles that have already been rooted previously.

The only good reason to allow the user to "lock" *150 again is to make it flashable from Assistant again.  I should adjust this as it's not working properly currently with wtfos-system remove in combination with margerine (due to different target files like mentioned).

I hope that made sense.

**Comment by stylesuxx** [comment]
Thank you for your feedback and explanations, added some TODOs I will look into.

> I'm sure you'll come across this in integration, but I'll make a quick note of it here: immediately after rooting, when I navigate to the wtfos page (or other adb reliant pages), they are completely blank. A refresh fixes this.

Yes, I have noticed that and started to fix it yesterday, not there yet.

> For going back to stock: I made wtfos-system uninstall persist the adb unlock and since it's targeting a different file than margerine used to, running margerine.js lock won't "relock" properly anymore.
> 
> You can use this to disable the remaing adb enables on *150:
> 
> ```
> sed -i '/#wtfos/,/#\/wtfos/d' /system/bin/${WTFOS_TARGET_SCRIPT}
> restorecon /system/bin/${WTFOS_TARGET_SCRIPT}
> ```
> 
> where WTFOS_TARGET_SCRIPT is either start_dji_system.sh or prestart_dji_system.sh on *150 and gl170 respectively.

Does this mean the last step (installStartup) during unlock is not actually needed, because wtfos-system does that?

> It's worth noting that this doesn't actually fully undo the "root", because the permanent secure_debug 1 flag is never removed (it's a bad idea for several reasons to allow that to be reset to 0). On gl170 you just loose the selinux unlock. On *150 you loose adb access however. This effectively makes the initial OTA one time secure debug action a NOP since the device is already permanently secure_debug 1. The latter matters a little bit on gl170, because it makes it harder to test for situation that causes you to require to run the root multiple times and reboot - since secure_debug=1 it's impossible to repro the e0 situation on Goggles that have already been rooted previously.
> 
> The only good reason to allow the user to "lock" *150 again is to make it flashable from Assistant again. I should adjust this as it's not working properly currently with wtfos-system remove in combination with margerine (due to different target files like mentioned).
> 
> I hope that made sense.

Yes, that makes sense. I just want to be as close to a "fresh" device as possible.

**Comment by j005u** [comment]
> OK, Interestingly I only experience this on the Vista - I was wondering if my connection simply was unstable, but yeah - that explains it.

Similarly to this behavior, *150 in secure_debug=1 mode comes up without the adb interface at first and adb is only enabled after the modified startup scripts are run. gl170 enables adb automatically on bootup _but_ you get an access denied error for any commands/pulls/pushes until the startup scripts have disabled selinux.

> Does this mean the last step (installStartup) during unlock is not actually needed, because wtfos-system does that?
It's needed on *150 to get adb to be able to push busybox/forward ports/get feedback on the install command. It's not needed on gl170 and in fact I removed it but had forgotten to push the unobfuscated version until yesterday.

I'll also note that installStartup uses the old margerine target script (that is present on all devices) for simplicity sake and different comment tags. postinst for wtfos-system is aware of this and cleans it.

Theoretically it might be possible to adapt the bootstrap script / wtfos-postinst to run purely on the shellexec but the two main concerns are dropping busybox and networking. It's probably possible (harder from the browser) through some convoluted means, but likely not worth the effort.

**Comment by j005u** [comment]
PS: don't bother implementing this
```
sed -i '/#wtfos/,/#\/wtfos/d' /system/bin/${WTFOS_TARGET_SCRIPT}
restorecon /system/bin/${WTFOS_TARGET_SCRIPT}
```

I think what I'll do is drop an extra "binary" in /system/bin after wtfos-system uninstall that you can invoke (manually or via configurator) to "fully clean up"/lock if you wish to.

**Comment by stylesuxx** [comment]
> I think what I'll do is drop an extra "binary" in /system/bin after wtfos-system uninstall that you can invoke (manually or via configurator) to "fully clean up"/lock if you wish to.

I think that would be nice, although I guess locking might be an edge case for development anyway (maybe for people trying to return their device within the warranty period?)

**Comment by j005u** [comment]
> I think what I'll do is drop an extra "binary" in /system/bin after wtfos-system uninstall that you can invoke (manually or via configurator) to "fully clean up"/lock if you wish to.

`wtfos-remove-adb -q` will remove the cmdline bindmount and selinux disable. The script is only dropped in /system/bin during wtfos-system uninstall.

Released with wtfos-system v0.1.15.

**Comment by Alia5** [comment]
I've just sucessfully rooted an OG AirUnit from the WebGui.  

I also installed WTFOS on v1 Goggles (did root via margarine, though)

**Comment by stylesuxx** [comment]
> I've just sucessfully rooted an OG AirUnit from the WebGui.

Awesome, thanks for the feedback!
