### ISSUE TITLE
In-flight reboot of dji goggle v2

### ISSUE THREAD

**Issue by Ti-Peres** [fpv-wtf/wtfos-configurator#404]
### Device

Goggles V2

### Operating System (Including version)

01.07.0000

### Browser

Chrome

### Trace ID (bottom left of the configurator screen)

7927d9f7-52f7-4cee-92de-29c79b264232

### Describe the issue

Hello, I know that the problem of restarting in flight is known by the community and also the devs of wtfos. I just wanted to share my experience because I noticed that this problem occurs in my case that I have flown several batteries about 5-6 of 5min each approximately. If I fly 2 to 3 batteries of 5 min each per fly and I restart my goggle dji the problem does not occur. I wonder if the heat is not a problem or if there is a saturation at the level of data. I had the problem with dji firmware 01.00.0606 and the latest wtfos update. I recently did the wtfos butter super pack V01.07.0000 update and I still have the problem of rebooting in flight. The vtx are caddix vista
V 01.00.0608 all up to date on wtfos as well. So in summary restart your dji goggle after 2 or 3 batteries of 5 min each and the problem will not arise. I hope this will help you

**Comment by UglyBabyGaming** [comment]
This Needs RE-OPENING !!!!!
 there is still a bug just had 2 reboots in the last five minute's  DJI V2 goggles only installed the wtfos last week.. I feel there is increased latency since using this wtfos osd also need to note my Sandisc 128gb sd card kept recording really late into the flight... the fcc hack was done last year no problems and still on there as I don't know how it would get removed.. Is this interfearing ??? (using vistas)
