### ISSUE TITLE
WTFOS is no longer recognized

### ISSUE THREAD

**Issue by Blueforcer** [fpv-wtf/wtfos-configurator#87]
After successful root, installing of WTFOS and MSP-OSD it isnt recognized anymore. It works great on my desk directly after installing. but at the next day nothing works anymore.
The configurator says i need to install WTFOS again on my vista, but the installation tooks only 2s and nothing changes. I tried different browsers, cables and reboot my vista many many times.
im not able to use WTFOS on my vista anymore

**Comment by stylesuxx** [comment]
on the bottom left in the configurator where it says "Trace ID" - can you please post that? Also just to be clear, you can still connect to the vista and you can interact through the CLI tab, right?

**Comment by Blueforcer** [comment]
Trace-ID:
5774e928-650c-4cb5-8ec0-ed69519dadbd
Yes CLI is working, its also still rooted

**Comment by stylesuxx** [comment]
Unfortunately I can't find any logs with that ID - when did you last try to install WTFOS?
Could you please run the following commands from the CLI and post the output:
```
cat /blackbox/wtfos.log
cat /blackbox/dinit.log
dinitctl list
opkg list-installed
df /blackbox/
df /
```

**Comment by Blueforcer** [comment]
i tried to install it 5min before opening this issue. also started again right now

output:

```
root@pigeon_wm150_tiny:/ # cat /blackbox/wtfos.log
wtfos: system loopmounted
wtfos: ran dji startup script
wtfos: started entware unslung
wtfos: system loopmounted
wtfos: ran dji startup script
wtfos: started entware unslung
wtfos: system loopmounted
wtfos: ran dji startup script
wtfos: started entware unslung
wtfos: system loopmounted
wtfos: ran dji startup script
wtfos: started entware unslung
wtfos: system loopmounted
wtfos: ran dji startup script
wtfos: started entware unslung
wtfos: system loopmounted
wtfos: ran dji startup script
wtfos: started entware unslung
root@pigeon_wm150_tiny:/ # cat /blackbox/dinit.log
dinit: service boot started.
dinit: service msp-osd-airside started.
dinit: service msp-osd-airside started.
dinit: service boot started.
dinit: service msp-osd-airside started.
dinit: service boot started.
dinit: service msp-osd-airside started.
dinit: service boot started.
dinit: service msp-osd-airside started.
dinit: service boot started.
dinit: service msp-osd-airside started.
dinit: service boot started.
root@pigeon_wm150_tiny:/ # dinitctl list
/system/bin/sh: dinitctl: not found
127|root@pigeon_wm150_tiny:/ # opkg list-installed
/system/bin/sh: opkg: not found
127|root@pigeon_wm150_tiny:/ # df /blackbox/
Filesystem               Size     Used     Free   Blksize
/blackbox/               1.5G   474.9M     1.0G   4096
root@pigeon_wm150_tiny:/ # df /
Filesystem               Size     Used     Free   Blksize
/                      308.8M     1.4M   307.4M   4096
root@pigeon_wm150_tiny:/ # 
```

**Comment by stylesuxx** [comment]
It seems as if everything is in place but not properly mounted on startup for some reason (although it worked a couple of times, according to the logs).

Could you please run:
```
/blackbox/opt/bin/opkg list-installed
```

just to make sure that the files are actually in place. I am afraid you will have to jump on the discord and we might have a 1 on 1 session to see what's going on in detail.

**Comment by Blueforcer** [comment]
Already done in your last post:
root@pigeon_wm150_tiny:/ # /blackbox/opt/bin/opkg list-installed
/system/bin/sh: /blackbox/opt/bin/opkg: not found

im already at your discord server ( Blueforcer#0001)

**Comment by j005u** [comment]
His wtfos slot had been corrupted (refused to boot) _and_ configurator failed to install in 2nd slot.

We've recently seen the same behavior of refusing to install to 2nd slot on Goggles too, I will investigate this independently.

Why his wtfos slot was corrupt and refused to boot is hard to diagnose without serial boot logs. We'll have to keep our eyes open for more such cases.

**Comment by stylesuxx** [comment]
Alright - thank you. So technically this is not a problem of the configurator. It would still be good to have some way of showing that there is this issue. @j005u any input on what I could check to deliver some useful information to the user?

**Comment by j005u** [comment]
Okay, so yes, this happens when wtfos is installed in the current not active slot, because our packages are still installed in `/blackbox/wtfos/opt/` (blackbox is shared across slots as id /data) and therefor the wtfos-system postinstall script never gets run (unless there's an update available).

In order to determine that this is the case, we need to look at $WTFOS_TARGET_SCRIPT (depending on the device) in /system/bin/ to see if it has the #wtfos comment tags. However, we can't see this, if wtfos is running, because we're not seeing the real /system. We could unmount our overlay, but the easier way is to just check the inactive partitions script.

```
mkdir /tmp/systwo
mount -t ext4 /dev/block/platform/soc/f0000000.ahb/f0400000.dwmmc0/mirror/system_2 /tmp/systwo
if grep -q "#wtfos" /system/bin/$WTFOS_TARGET_SCRIPT; then
    echo "ruh roh raggy" 
fi
```
Mind, `mirror ` gives us partitions according to the currently active slot (system is the active and system_2 is the inactive slot) while `by-name` would give us the physical partition map layout, i.e. by order in flash.

Do determine if the inactive slot is corrupted, we can look at `unrd` output.
```
root@pigeon_wm170_gls:/ # unrd
switch_product          0
running_cp_status               wm169_gls
slot_1.status_bootable          1
force_ota               no
slot_2.system_md5               ac37f4ca76d4dcdcaf0de471e8799d94
slot_2.status_bootable          1
boot.mode               none
slot_2.status_successful                1
slot_1.status_active            1
slot_2.status_active            0
product_type            wm150_gls
product_type_switch             1
HW_VER          09.03.02.00
dji.build.version               10.00.16.84
lk_log_num              0
wipe_counter            0
crash_counter           0
slot_1.status_successful                1
```

We care about `slot_1.status_active` and `slot_2.status_active` . Whichever values is 1 tells us which slot we are booted into. Next we look at `slot_1.status_successful` or `slot_2.status_successful` we can determine if the inactive slot was unable to boot, i.e. "is corrupted". If not, could also change back to the inactive slot with `unrd $key $value` to flip the `status_active` values around and reboot to the other slot, but then the question remains how we got here in the first place.

One way it could happen on V2 goggles specifically is related to the low battery issue on 0606 where all unrd values get reset. This would occur If the user was on slot 2 when first installing wtfos (which can happen if they previously had an interruption during fw flashing).

If the inactive slot does not appear to be corrupt, we _could_ attempt to switch to it. But it may also result in unknown issues potentially.

If the inactive slot is corrupt, we should re-flash it. The most readily available method would be to just `dd if=/dev/block/platform/soc/f0000000.ahb/f0400000.dwmmc0/mirror/system of=/dev/block/platform/soc/f0000000.ahb/f0400000.dwmmc0/mirror/system_2 bs=1M`, after which we should wipe the wtfos install in /blackbox/wtfos/ for good measure, switch slots with unrd and reboot.

Should this reside in the configurator or in a purpose built health check script in /blackbox/wtfos? It could also be possible for /blackbox/wtfos to be gone, but the inactive slot to still be corrupt. I don't mind either way.

**Comment by stylesuxx** [comment]
> Should this reside in the configurator or in a purpose built health check script in /blackbox/wtfos? It could also be possible for /blackbox/wtfos to be gone, but the inactive slot to still be corrupt. I don't mind either way. One could also argue that we should always switch to slot_1 before wtfos install, that way any unrd reset issues don't ruin the day and require intervention. This should then be followed by status_successful verification to make sure we indeed ended up in the correct slot.

If `/blackbox/wtfos` can be gone, I would rather like to see it implemented in the configurator. I like the idea of switching to slot_1. From what I understand I think the following order of implementation would make the most sense:

1. Detection of corrupted slot
2. User feedback that slot is corrupted
3. Re-flashing after user confirmation
4. WTFOS installation to Slot 1

**Comment by j005u** [comment]
Yes, that sounds about right.

Regarding 4) - switching to slot 1 should be part of the general install process, always checking active slot before install.

The corruption detection should probably be on every connect, if adb is available but wtfos is not found in path.

**Comment by j005u** [comment]
I wrote a simple bash script that fixes things and cleans up slot_2 for good measure, if the user has ota.zip present.

See here: https://github.com/fpv-wtf/margerine/wiki/Troubleshooting#wtfos-install-stuck-in-a-loop

As is it applies to wtfos being installed in slot_2 and unrd getting reset. It would not for example solve slot_1 being corrupt and unable to boot and us being in slot_2.

@stylesuxx how far along are you in implementing the above discussed mechanism into the configurator?

I might propose that if you haven't gone far with it yet, that install should switch to slot_1 to avoid issues with unrd getting reset, but not much more. There is one however here - if switching slots on anything other than v2 goggles, we need to either re-root after rebooting _or_ patch slot_1s wtfos target script so that adb is enabled on startup (margerine step 5) before rebooting.

The troubleshooting logic we could literally implement as a health check scripts ran at connection time that verifies everything is healthy, stored in the configurator. If not, the user is notified of this and automatic fixes can be attempted, again via shell script and further instructions if needed as well as status simply being script echo output.

I imagine we could have a folder of such scripts in the configurator source, where each script can be called with "check" or "fix" parameters. I think this might be quicker and easier to maintain than bespoke js logic.

Thoughts? To be clear, I have nothing against bespoke JS logic, if we're able to implement. But we have a lot more people in the team that could maintain such bash scripts.

**Comment by j005u** [comment]
We discussed modifying step 5 earlier, but I figured we can do this even easier in step 3, by simply adding: 
```
unrd slot_2.status_active 0
unrd slot_1.status_active 1
```
to the existing shell payload.

That way by the time secure debug is active we will also have already rebooted to the correct slot.

**Comment by j005u** [comment]
Following on from that, wtfos install should:
- check that the output of `unrd slot_2.status_active` = 0
- check that the output of `unrd slot_1.status_active` = 1
- check that the output of `slot_1.status_successful` = 1
- if yes, proceed to install
- if not execute unrd `slot_2.status_active 0 && unrd slot_1.status_active 1`
- reboot
- repeat checks 1-3
- if yes, proceed to install
- if no, dump unrd for debug and ask to contact support
   - slot 1 could be corrupt and unbootable for example

**Comment by j005u** [comment]
Notes from testing the health checks implementation:

- We should always re-run health checks when an adb device is connected, otherwise when switching devices any errors on the new device would not be picked up. I think it's better to just re-run them rather than trying to keep track of devices x health checks x state.
- For v2 Goggles specifically, health checks are not properly re-run after a reboot, because of the 2-3 second selinux enabled window which causes `- exec '/system/bin/sh' failed: Permission denied (13) -` on any adb commands. We don't know of any way to fix this on v2s.
- We should solve this ideally by not considering the adb state to be connected until health-checks have been able to properly run (failing or passing) and only then proceed to populate the rest of configurator state. I think it's theoretically enough to check for the permission denied error on any adb responses, wait a second and try again. We should set a reasonable retry limit, but unless something goes horribly wrong in a new and exotic way, this shouldn't happen.
- Unit 4 doesn't trigger a reboot, because it doesn't need to. If "fix" exits cleanly without a reboot, we should re-run health checks.
- Let's rename "Healthchecks" to "health checks"
- Modified notice text for the user: "Don't worry, this is normal and can happen due to various reasons, including bugs in the underlaying operating system. The configurator can help you fix these issues. When attempting an automated fix, your device might reboot in the process. In some specific cases you may need to re-root your device after a reboot, before health checks can continue."
- The attempt fix button could really use some visual feedback like a spinner, otherwise fixes that take 1 minute + can be confusing for the user.

Really close! Great work so far @stylesuxx.

**Comment by j005u** [comment]
@stylesuxx yup, seems good to go.

🎉
